export const SHOW_SKILL_DETAIL_MODAL = 'SHOW_SKILL_DETAIL_MODAL'
export const HIDE_SKILL_DETAIL_MODAL = 'HIDE_SKILL_DETAIL_MODAL'
export const SHOW_INFO_MODAL = 'SHOW_INFO_MODAL'
export const HIDE_INFO_MODAL = 'HIDE_INFO_MODAL'
